# Schedule {-}

## Week 1: 1/24 {-}

- **Friday:** Introductions; a taste of R and visualization

## Week 2: 1/27 - 1/31 {-}

- **Monday:** Univariate visualization and summary measures    
    **Before class:** Follow all instructions on the [Software Setup] page. Read sections 1.1, 2.1-2.4, and 2.6 in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Data; Univariate Summaries and Visualization.
- **Wednesday:** Bivariate visualization and summary measures    
    **Before class:** Read sections 2.5, 2.7, and 2.8 in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Bivariate Summaries and Visualization.
- **Friday:** Continue with bivariate visualization.    
    **No new reading or Moodle questions.** Just work on Homework 1.

<span style="color:red">
Homework 1 (on Moodle) is due Friday, January 31 at midnight.
</span>

## Week 3: 2/3 - 2/7 {-}

- **Monday:** Simple linear regression models    
    **Before class:** Read sections 3.1 to 3.6 in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Simple Linear Regression (Part 1).
- **Wednesday:** Model evaluation and categorical predictors    
    **Before class:** Read section 3.8 in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html) only up through section 3.8.1 Indicator Variables, and answer the Moodle questions under Reading Checks > Simple Linear Regression (Part 2).
- **Friday:** Quiz 1 in class

<span style="color:red">
Homework 2 (on Moodle) is due Thursday, February 13 at midnight.
</span>

## Week 4: 2/10 - 2/14 {-}

<span style="color:red">
Reminder: Homework 2 (on Moodle) is due Thursday, February 13 at midnight.
</span>

- **Monday:** Multiple linear regression models    
    **Before class:** Read sections 3.8.1 (Indicator Variables), 3.8.3 (Causation), and 3.8.6 (Dealing with Non-Linear Relationships) in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Multiple Linear Regression.
- **Wednesday:** Multiple linear regression models    
    **Before class:** No new reading.
- **Friday:** Interaction models    
    **Before class:** Read section 3.8.2 (Interaction Variables) in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Interaction Models.

## Week 5: 2/17 - 2/21 {-}

No new readings this week.

<span style="color:red">
Homework 3 is due Sunday, February 23 at midnight.
</span>

- **Monday:** Review multiple linear regression models and interaction.
- **Wednesday:** Variable redundancy, multicollinearity, and adjusted R-squared.
- **Friday:** Quiz 2 in class

We'll shift to new groups next week.

## Week 6: 2/24 - 2/28 {-}

New groups starting this week.

For class on Monday, bring a pair of earbuds/headphones, and come prepared to listen to some loud music as part of an experiment!

<span style="color:red">
No class on Friday, but you must go to 2 capstone talks and submit a short response. On Moodle see Homework > Capstone Days.
</span>

- **Monday:** Class experiment! Quantifying uncertainty    
    **Before class:** Read sections 2.7.3 (Is this a Real Difference?) and 3.8.5 (Is the Difference Real?) in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Quantifying Uncertainty.
- **Wednesday:** Causal inference    
    **Before class:** Read sections 1.6 (Causal Inference) and 3.8.3 (Causation) in the [STAT 155 Notes](https://bcheggeseth.github.io/Stat155Notes/index.html), and answer the Moodle questions under Reading Checks > Causal Inference.

## Week 7: 3/2 - 3/6 {-}

No new readings this week - same topics that you had readings for last week.

- **Monday:** Bootstrapping.
- **Wednesday:** Causal inference.
- **Friday:** Quiz 3 in class

## Week 8: 3/9 - 3/13 {-}

- **Monday:** Article discussion.    
    **Before class:** Please read the article [How racial discrimination in law enforcement actually works](https://www.vox.com/2014/12/1/7311417/race-law-controls).
- **Wednesday:** Review for the midterm.
- **Friday:** Midterm in class

## Spring Break: 3/16 - 3/27 {-}

## Week 9: 3/30 - 4/3 {-}

<span style="color:red">
If Google/YouTube access is a problem, all videos and slides are also available on Moodle in the "Videos & Slides" section. All Moodle questions are in the "Reading / Video Checks" section.
</span>

- **Monday:** Probability and odds.    
    - Video: Probability Essentials ([YouTube link](https://youtu.be/O0voTrgOtQw), [Slides](https://drive.google.com/file/d/1gSOEzbvQKJBf9ozJGdowaVPLNFh-XdUC/view?usp=sharing))
    - Moodle questions: Probability Essentials
- **Wednesday:** Introduction to logistic regression.    
    - Video: Logistic Regression ([YouTube link](https://youtu.be/yi7I2vmxbiQ), [Slides](https://drive.google.com/file/d/1o5WwSnShEazkV_HTWtOCeK4W0snrsep3/view?usp=sharing))
    - Moodle questions: Logistic Regression
- **Friday:** Continuing with logistic regression. No new video or Moodle questions.

## Week 10: 4/6 - 4/10 {-}

- **Monday:** Multiple logistic regression
- **Wednesday:** Sampling distributions and the normal distribution
    - Video: Sampling Distributions ([YouTube link](https://youtu.be/hR3h7VGA3Sc), [Slides](https://drive.google.com/file/d/1HRij3BtATblO9uzeoxGHyirI0b3zzu9D/view?usp=sharing))
- **Friday:** The central limit theorem and confidence intervals
    - Video: Central Limit Theorem (YouTube link will be added soon, [Slides](https://drive.google.com/file/d/1E4ARLYbdq_YAX8vK28KenAH1mbL3W0wm/view?usp=sharing))



