---
title: "Hypothesis Testing"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Setup

We will be using data on 1167 colleges obtained from an edition of the U.S. News College Rankings. For each college, the following variables are given:

- `College`: Name of school
- `GradRate`: College graduation rate (as a value from 0 to 100)
- `SFRatio`: Student-to-faculty ratio
- `AdmisRate`: Percentage of applicants accepted (as a value from 0 to 100)
- `FacultyPhD`: Percentage of faculty with a PhD (as a value from 0 to 100)
- `Type`: School type (Private or Public)
- `Region`: Location of school: Midwest, NorthEast, South, or West.
- `State`: School state
- `MathSAT`: Average Math SAT score of entering first-years
- `VerbalSAT`: Average Verbal SAT score of entering first-years
- `ACT`: Average ACT score of entering first-years

```{r}
library(readr)
library(dplyr)
library(ggplot2)

colleges <- read_csv("https://www.dropbox.com/s/efgkjbqeiikzzn7/USNews.csv?dl=1")
```

> **Research question:** What is the causal effect of student-to-faculty ratios on graduation rates? How does this effect differ across school types?

Throughout, use zero as the criteria for a meaningful difference and a significance level of 0.01.





## Exercise 1

### Part a

Fit an *unadjusted* model that ignores these potential confounders. Present a (naïve) answer to the first research question by interpreting the relevant coefficient and conducting an appropriate hypothesis test.

### Part b

What would you expect about the corresponding 99% confidence interval (CI) for the coefficient (whether through bootstrapping or the CLT)? What about the 95% CI for the coefficient? Briefly explain, and check your answer with `confint()`.





## Exercise 2

We find that school type (`Type`) and average ACT scores (`ACT`) are potential confounders of the relationship between student-to-faculty ratios and graduation rates.

### Part a

Fit an *adjusted* model that answers the first research question. **Give an interpretation** for all 4 quantities for the relevant coefficient: the estimate, the standard error, the test statistic, and p-value.

### Part b

Show that you reach the same conclusions with an appropriate confidence interval.





## Exercise 3

Fit an appropriate model to answer the second research question. Support your response by interpreting the two relevant coefficients and by appropriately using a p-value and a confidence interval.

Given the hypotheses you stated above, briefly explain why the p-value on `(Intercept)` is so small.





## Exercise 4

Suppose we know that the distribution of a test statistic $Z$ "under $H_0$" (if $H_0$ is true) is the standard normal distribution (mean = 0, SD = 1). This is the case in logistic regression.

### Part a

For what values of the test statistic $Z$ will I reject $H_0$ using $\alpha = 0.05$ as my p-value cutoff?

### Part b

For what values of the test statistic $Z$ will I reject $H_0$ using $\alpha = 0.32$ as my p-value cutoff?


