<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Topic 12 Bootstrapping | STAT 155: Introduction to Statistical Modeling</title>
  <meta name="description" content="This is the class website for STAT 155 at Macalester College." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Topic 12 Bootstrapping | STAT 155: Introduction to Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the class website for STAT 155 at Macalester College." />
  <meta name="github-repo" content="lmyint/155_spring_2020" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Topic 12 Bootstrapping | STAT 155: Introduction to Statistical Modeling" />
  
  <meta name="twitter:description" content="This is the class website for STAT 155 at Macalester College." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="experiment.html"/>
<link rel="next" href="causal-inference.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #2a211c; color: #bdae9d; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; background-color: #2a211c; color: #bdae9d; border-right: 1px solid #bdae9d; }
td.sourceCode { padding-left: 5px; }
pre, code { color: #bdae9d; background-color: #2a211c; }
code > span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
code > span.dt { text-decoration: underline; } /* DataType */
code > span.dv { color: #44aa43; } /* DecVal */
code > span.bn { color: #44aa43; } /* BaseN */
code > span.fl { color: #44aa43; } /* Float */
code > span.ch { color: #049b0a; } /* Char */
code > span.st { color: #049b0a; } /* String */
code > span.co { color: #0066ff; font-style: italic; } /* Comment */
code > span.al { color: #ffff00; } /* Alert */
code > span.fu { color: #ff9358; font-weight: bold; } /* Function */
code > span.er { color: #ffff00; font-weight: bold; } /* Error */
code > span.wa { color: #ffff00; font-weight: bold; } /* Warning */
code > span.cn { } /* Constant */
code > span.sc { color: #049b0a; } /* SpecialChar */
code > span.vs { color: #049b0a; } /* VerbatimString */
code > span.ss { color: #049b0a; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { font-weight: bold; } /* Preprocessor */
code > span.at { } /* Attribute */
code > span.do { color: #0066ff; font-style: italic; } /* Documentation */
code > span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
code > span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
code > span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">STAT 155: Intro to Stat Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a><ul>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-1-124"><i class="fa fa-check"></i>Week 1: 1/24</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-2-127---131"><i class="fa fa-check"></i>Week 2: 1/27 - 1/31</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-3-23---27"><i class="fa fa-check"></i>Week 3: 2/3 - 2/7</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-4-210---214"><i class="fa fa-check"></i>Week 4: 2/10 - 2/14</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-5-217---221"><i class="fa fa-check"></i>Week 5: 2/17 - 2/21</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-6-224---228"><i class="fa fa-check"></i>Week 6: 2/24 - 2/28</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-7-32---36"><i class="fa fa-check"></i>Week 7: 3/2 - 3/6</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-8-39---313"><i class="fa fa-check"></i>Week 8: 3/9 - 3/13</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#spring-break-316---327"><i class="fa fa-check"></i>Spring Break: 3/16 - 3/27</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-9-330---43"><i class="fa fa-check"></i>Week 9: 3/30 - 4/3</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-10-46---410"><i class="fa fa-check"></i>Week 10: 4/6 - 4/10</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-11-413---417"><i class="fa fa-check"></i>Week 11: 4/13 - 4/17</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a><ul>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html#troubleshooting"><i class="fa fa-check"></i>Troubleshooting</a></li>
</ul></li>
<li class="part"><span><b>I Describing and Visualizing Data</b></span></li>
<li class="chapter" data-level="1" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html"><i class="fa fa-check"></i><b>1</b> Welcome and Motivation</a><ul>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#introductions"><i class="fa fa-check"></i>Introductions</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#a-taste-of-data-visualization-in-r"><i class="fa fa-check"></i>A taste of data visualization in R</a><ul>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#warm-up"><i class="fa fa-check"></i>Warm-up</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-1"><i class="fa fa-check"></i>Phase 1</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-2"><i class="fa fa-check"></i>Phase 2</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-3"><i class="fa fa-check"></i>Phase 3</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-4"><i class="fa fa-check"></i>Phase 4</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-5"><i class="fa fa-check"></i>Phase 5</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-6"><i class="fa fa-check"></i>Phase 6</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-7"><i class="fa fa-check"></i>Phase 7</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html"><i class="fa fa-check"></i><b>2</b> Univariate Visualization and Data Summaries</a><ul>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#learning-goals"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#discussion"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#exercises"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#part-1"><i class="fa fa-check"></i>Part 1</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#part-2"><i class="fa fa-check"></i>Part 2</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#extra"><i class="fa fa-check"></i>Extra!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html"><i class="fa fa-check"></i><b>3</b> Bivariate Visualization - Part 1</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#learning-goals-1"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercises-1"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#context-and-setup"><i class="fa fa-check"></i>Context and Setup</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#extra-1"><i class="fa fa-check"></i>Extra!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html"><i class="fa fa-check"></i><b>4</b> Bivariate Visualization - Part 2</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#learning-goals-2"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercises-2"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-1-2"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-2-2"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-4-2"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-5-1"><i class="fa fa-check"></i>Exercise 5</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-6"><i class="fa fa-check"></i>Exercise 6</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Linear Regression Modeling</b></span></li>
<li class="chapter" data-level="5" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html"><i class="fa fa-check"></i><b>5</b> Modeling Concepts (Part 1)</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#learning-goals-3"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#new-groups"><i class="fa fa-check"></i>New Groups!</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#discussion-1"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercises-3"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-1-3"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-2-3"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-3-3"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-4-3"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-5-2"><i class="fa fa-check"></i>Exercise 5</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html"><i class="fa fa-check"></i><b>6</b> Modeling Concepts (Part 2)</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#learning-goals-4"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#warm-up-1"><i class="fa fa-check"></i>Warm-up</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#discussion-2"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercises-4"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercise-1-4"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercise-2-4"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#learning-goals-5"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#discussion-and-exercises"><i class="fa fa-check"></i>Discussion and Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="interaction-models.html"><a href="interaction-models.html"><i class="fa fa-check"></i><b>8</b> Interaction Models</a><ul>
<li class="chapter" data-level="" data-path="interaction-models.html"><a href="interaction-models.html#learning-goals-6"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="interaction-models.html"><a href="interaction-models.html#discussion-and-exercises-1"><i class="fa fa-check"></i>Discussion and Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="redundancy-multicollinearity-and-adjusted-r-squared.html"><a href="redundancy-multicollinearity-and-adjusted-r-squared.html"><i class="fa fa-check"></i><b>9</b> Redundancy, Multicollinearity, and Adjusted R-squared</a><ul>
<li class="chapter" data-level="" data-path="redundancy-multicollinearity-and-adjusted-r-squared.html"><a href="redundancy-multicollinearity-and-adjusted-r-squared.html#learning-goals-7"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="redundancy-multicollinearity-and-adjusted-r-squared.html"><a href="redundancy-multicollinearity-and-adjusted-r-squared.html#discussion-3"><i class="fa fa-check"></i>Discussion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="review.html"><a href="review.html"><i class="fa fa-check"></i><b>10</b> Review</a><ul>
<li class="chapter" data-level="" data-path="review.html"><a href="review.html#task"><i class="fa fa-check"></i>Task</a></li>
</ul></li>
<li class="part"><span><b>III Quantifying Uncertainty and Causal Inference</b></span></li>
<li class="chapter" data-level="11" data-path="experiment.html"><a href="experiment.html"><i class="fa fa-check"></i><b>11</b> Experiment!</a><ul>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#motivation"><i class="fa fa-check"></i>Motivation</a></li>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#experiment-1"><i class="fa fa-check"></i>Experiment</a></li>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#analysis-and-discussion"><i class="fa fa-check"></i>Analysis and Discussion</a><ul>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#part-1-comparing-the-groups"><i class="fa fa-check"></i>Part 1: Comparing the groups</a></li>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#part-2-is-this-a-real-difference"><i class="fa fa-check"></i>Part 2: Is this a real difference?</a></li>
<li class="chapter" data-level="" data-path="experiment.html"><a href="experiment.html#part-3-study-design"><i class="fa fa-check"></i>Part 3: Study design</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrapping.html"><a href="bootstrapping.html"><i class="fa fa-check"></i><b>12</b> Bootstrapping</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#learning-goals-8"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#discussion-4"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#exercises-5"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#data-setup"><i class="fa fa-check"></i>Data setup</a></li>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#exercise-1-5"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="bootstrapping.html"><a href="bootstrapping.html#exercise-2-5"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>13</b> Causal Inference</a><ul>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#learning-goals-9"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#discussion-5"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#exercises-6"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#exercise-1-6"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#exercise-2-6"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="causal-inference.html"><a href="causal-inference.html#exercise-3-4"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Review</b></span></li>
<li class="chapter" data-level="14" data-path="midterm-review.html"><a href="midterm-review.html"><i class="fa fa-check"></i><b>14</b> Midterm Review</a><ul>
<li class="chapter" data-level="" data-path="midterm-review.html"><a href="midterm-review.html#core-themes"><i class="fa fa-check"></i>Core Themes</a></li>
<li class="chapter" data-level="" data-path="midterm-review.html"><a href="midterm-review.html#additional-exercises"><i class="fa fa-check"></i>Additional Exercises</a><ul>
<li class="chapter" data-level="" data-path="midterm-review.html"><a href="midterm-review.html#exercise-1-7"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="midterm-review.html"><a href="midterm-review.html#exercise-2-7"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="midterm-review.html"><a href="midterm-review.html#exercise-3-5"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Logistic Regression Modeling</b></span></li>
<li class="chapter" data-level="15" data-path="probability-essentials.html"><a href="probability-essentials.html"><i class="fa fa-check"></i><b>15</b> Probability Essentials</a><ul>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#learning-goals-10"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercises-7"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-1-binary-responses"><i class="fa fa-check"></i>Exercise 1: Binary responses</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-2-probability"><i class="fa fa-check"></i>Exercise 2: Probability</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-3-odds-from-probability"><i class="fa fa-check"></i>Exercise 3: Odds from probability</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-4-probability-from-odds"><i class="fa fa-check"></i>Exercise 4: Probability from odds</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-5-maryland-renaissance-fair"><i class="fa fa-check"></i>Exercise 5: Maryland Renaissance Fair</a></li>
<li class="chapter" data-level="" data-path="probability-essentials.html"><a href="probability-essentials.html#exercise-6-disease-screening"><i class="fa fa-check"></i>Exercise 6: Disease screening</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html"><i class="fa fa-check"></i><b>16</b> Simple Logistic Regression</a><ul>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#learning-goals-11"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#warm-up-2"><i class="fa fa-check"></i>Warm-up</a></li>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#exercises-8"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#exercise-1-8"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#exercise-2-8"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#exercise-3-6"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="simple-logistic-regression.html"><a href="simple-logistic-regression.html#exercise-4-4"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html"><i class="fa fa-check"></i><b>17</b> Multiple Logistic Regression</a><ul>
<li class="chapter" data-level="" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html#learning-goals-12"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html#exercises-9"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html#exercise-1-9"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html#exercise-2-9"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="multiple-logistic-regression.html"><a href="multiple-logistic-regression.html#exercise-3-7"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Statistical Inference</b></span></li>
<li class="chapter" data-level="18" data-path="sampling-distributions-and-the-normal-distribution.html"><a href="sampling-distributions-and-the-normal-distribution.html"><i class="fa fa-check"></i><b>18</b> Sampling Distributions and the Normal Distribution</a><ul>
<li class="chapter" data-level="" data-path="sampling-distributions-and-the-normal-distribution.html"><a href="sampling-distributions-and-the-normal-distribution.html#learning-goals-13"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="sampling-distributions-and-the-normal-distribution.html"><a href="sampling-distributions-and-the-normal-distribution.html#exercises-10"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>19</b> Central Limit Theorem</a><ul>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#learning-goals-14"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#discussion-6"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercises-11"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercise-1-10"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercise-2-10"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercise-3-8"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html"><i class="fa fa-check"></i><b>20</b> Linear Regression Assumptions</a><ul>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#learning-goals-15"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#discussion-7"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#exercises-12"><i class="fa fa-check"></i>Exercises</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#exercise-1-11"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#exercise-2-11"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#exercise-3-9"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="linear-regression-assumptions.html"><a href="linear-regression-assumptions.html#exercise-4-5"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>21</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#learning-goals-16"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#discussion-8"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercises-13"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercise-1-12"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercise-2-12"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercise-3-10"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercise-4-6"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html"><i class="fa fa-check"></i><b>22</b> Hypothesis Testing Errors</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#learning-goals-17"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercises-14"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercise-1-13"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercise-2-13"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercise-3-11"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercise-4-7"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-errors.html"><a href="hypothesis-testing-errors.html#exercise-5-3"><i class="fa fa-check"></i>Exercise 5</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 155: Introduction to Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bootstrapping" class="section level1">
<h1><span class="header-section-number">Topic 12</span> Bootstrapping</h1>
<div id="learning-goals-8" class="section level2 unnumbered">
<h2>Learning Goals</h2>
<ul>
<li>Explain the idea of the true population value for a quantity</li>
<li>Describe the steps and assumptions of the bootstrapping procedure and how it estimates sampling variation</li>
<li>Use bootstrap confidence intervals to answer research questions</li>
</ul>
<p><br><br><br><br></p>
</div>
<div id="discussion-4" class="section level2 unnumbered">
<h2>Discussion</h2>
<blockquote>
<p><strong>Research question:</strong> What is the causal effect of loud distractions on reaction times?</p>
</blockquote>
<ul>
<li>More on the “causal” part next time.</li>
<li>But for now, we will express “causal” as meaning: there is no influence of confounding variables.
<ul>
<li>Is this true? (You’ll check in the exercises.)</li>
</ul></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">original_model &lt;-<span class="st"> </span><span class="kw">lm</span>(rtime <span class="op">~</span><span class="st"> </span>arm, <span class="dt">data =</span> experiment)
<span class="kw">summary</span>(original_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = rtime ~ arm, data = experiment)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -117.09  -51.26   -2.09   37.74  324.91 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    318.26      13.35  23.843   &lt;2e-16 ***
## armTreatment    32.83      20.72   1.585    0.119    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 74.32 on 51 degrees of freedom
## Multiple R-squared:  0.04693,    Adjusted R-squared:  0.02824 
## F-statistic: 2.511 on 1 and 51 DF,  p-value: 0.1192</code></pre>
<ul>
<li>On average, those in the Treatment group (loud distractions) had reaction times that were 32.83 milliseconds higher than those in the Control group.</li>
<li>Is a difference of 32.83 ms a “real difference”?</li>
</ul>
<p><br><br><br><br></p>
<p><strong>What do we mean by “real difference”?</strong></p>
<ul>
<li>We <em>estimated</em> this difference based on our class <em>sample</em>.
<ul>
<li>This is why the <code>summary()</code> output from R labels the column <code>Estimate</code>.</li>
</ul></li>
<li>In reality, we care about understanding a general truth about the broader adult population.</li>
<li><strong>True population value:</strong> the value of the model coefficient that we would observe if we fit the model using the entire population of interest.
<ul>
<li>Remember that model coefficients give us changes/comparisons of interest.</li>
</ul></li>
<li>“Real difference” means a <em>meaningful</em> difference in the broader population
<ul>
<li>Maybe a meaningful difference is simply not zero.</li>
<li>Maybe a meaningful difference is one that is of a certain magnitude or higher. e.g., at least 100 ms.</li>
</ul></li>
</ul>
<p><br><br><br><br></p>
<p><strong>What is our best guess of the true population value?</strong></p>
<ul>
<li>Our estimate itself! (Our estimate from our sample.)</li>
<li>Hmm…but what if our sample was weird/peculiar somehow?</li>
<li>Would most other samples have generated similar estimates?
<ul>
<li>Another way of expressing this: how much do estimates vary from sample to sample?</li>
<li>If a lot: many samples estimate a difference with the opposite sign as mine! Not reassuring!</li>
<li>If not a lot: most samples at least agree on the sign of the difference. More reassuring that I got the sign of the true population value correct.</li>
</ul></li>
</ul>
<p><br><br><br><br></p>
<p><strong>Bootstrapping to estimate sampling variation</strong></p>
<ul>
<li>Can’t resample the population (easily), so let’s resample our sample!</li>
<li><strong>Goal:</strong> Only care about measuring <em>variation</em> in estimates from sample to sample.
<ul>
<li>Think range, standard deviation as metrics</li>
<li>Don’t care about the center of the estimates from sample to sample. (Because we’re resampling our sample, the center will essentially be equal to our original estimate.)</li>
</ul></li>
</ul>
<p><br><br><br><br></p>
<p><strong>The bootstrapping procedure</strong></p>
<ul>
<li>Step 1: Resample our sample a large number <span class="math inline">\(B\)</span> (<span class="math inline">\(\approx\)</span> 1000) times.
<ul>
<li>The resamples must be <strong>of the same size</strong> as the original. (Increasing the sample size decreases the amount of sampling variation.)</li>
<li>This resampling must be done <strong>with replacement</strong>. (Otherwise we’ll get the same resample every time.)</li>
</ul></li>
<li>Step 2: Fit the model of interest in each of the <span class="math inline">\(B\)</span> resamples.</li>
<li>Step 3: Obtain the coefficients of interest.</li>
</ul>
<p><br></p>
<p>We now have <span class="math inline">\(B\)</span> (1000) sets of coefficients.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Resample the data and estimate the difference</span>
<span class="kw">set.seed</span>(<span class="dv">89</span>)
resampled_coeffs &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, {
    experiment_resampled &lt;-<span class="st"> </span>experiment <span class="op">%&gt;%</span>
<span class="st">        </span><span class="kw">sample_n</span>(<span class="dt">size =</span> <span class="kw">nrow</span>(experiment), <span class="dt">replace =</span> <span class="ot">TRUE</span>)
    mod &lt;-<span class="st"> </span><span class="kw">lm</span>(rtime <span class="op">~</span><span class="st"> </span>arm, <span class="dt">data =</span> experiment_resampled)
    <span class="kw">coefficients</span>(mod)
})

<span class="co"># Put the resampled coefficients into a dataset</span>
bootstrap_data &lt;-<span class="st"> </span>resampled_coeffs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">t</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.data.frame</span>()

<span class="co"># What does bootstrap_data look like?</span>
<span class="kw">head</span>(bootstrap_data)</code></pre></div>
<pre><code>##   (Intercept) armTreatment
## 1    324.0714    19.648571
## 2    318.7273    37.122727
## 3    327.3182    19.843109
## 4    314.7429     6.090476
## 5    313.8077    21.896011
## 6    331.3784    37.621622</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Plot the distribution of the coefficient of interest</span>
<span class="kw">ggplot</span>(bootstrap_data, <span class="kw">aes</span>(<span class="dt">x =</span> armTreatment)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_histogram</span>()</code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="stat155_manual_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p><br></p>
<p>There are two main methods to quantify the amount of sampling variation.</p>
<p><strong>Method 1:</strong> Use the middle 95% of these coefficients</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># The $ pulls out the armTreatment variable</span>
<span class="kw">quantile</span>(bootstrap_data<span class="op">$</span>armTreatment, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</code></pre></div>
<pre><code>##      2.5%     97.5% 
## -7.614275 77.785810</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># The [[&quot;armTreatment&quot;]] also pulls out the armTreatment variable</span>
<span class="kw">quantile</span>(bootstrap_data[[<span class="st">&quot;armTreatment&quot;</span>]], <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</code></pre></div>
<pre><code>##      2.5%     97.5% 
## -7.614275 77.785810</code></pre>
<ul>
<li>Middle 95% is the range from -7.6 to 77.8 ms.</li>
<li>This is the <strong>95% bootstrap confidence interval</strong>.</li>
<li>This interval can be interpreted as a range of plausible values for the true population value (difference in reaction times: Treatment - Control).
<ul>
<li>After all, it represents a range of estimates from “other samples”.</li>
<li>A sample’s estimate is our best guess for the true population value.</li>
</ul></li>
<li>Do we have evidence for a real difference?
<ul>
<li>What is our criteria for a real difference? Not zero?
<ul>
<li>We <em>do not</em> have evidence for a real difference.</li>
<li>Zero is a plausible value for the true population difference because it is in the interval.</li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
<p>Suppose our 95% bootstrap confidence interval (CI) had been (90, 200)</p>
<ul>
<li>Criterion: a real difference is not zero
<ul>
<li>We <em>do</em> have evidence for a real difference.</li>
<li>Zero is not a plausible value for the true population value because it is not in the interval.</li>
</ul></li>
<li>Another criterion: a real difference is at least 100 ms.
<ul>
<li>We <em>do not</em> have evidence for a real difference because it is plausible that the true difference in the broader population is a value less than 100 ms (e.g., 90, 91, 92 are all plausible because they are in the interval).</li>
</ul></li>
</ul>
<p><br><br></p>
<p><strong>Method 2:</strong> If the 1000 coefficients <strong>follow a normal distribution</strong>…</p>
<ul>
<li>The middle 95% is given by: -2 SDs to +2 SDs</li>
<li>SD = standard deviation of the 1000 coefficients.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># SD measures the spread of the coefficient estimates across samples</span>
<span class="kw">sd</span>(bootstrap_data<span class="op">$</span>armTreatment)</code></pre></div>
<pre><code>## [1] 21.87694</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># It&#39;s quite close to the Standard Error (Std. Error)!</span>
<span class="co"># Not a coincidence!</span>
<span class="kw">summary</span>(original_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = rtime ~ arm, data = experiment)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -117.09  -51.26   -2.09   37.74  324.91 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    318.26      13.35  23.843   &lt;2e-16 ***
## armTreatment    32.83      20.72   1.585    0.119    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 74.32 on 51 degrees of freedom
## Multiple R-squared:  0.04693,    Adjusted R-squared:  0.02824 
## F-statistic: 2.511 on 1 and 51 DF,  p-value: 0.1192</code></pre>
<p>Method 1 is the most general (preferred way). We’ll see Method 2 in another way later in the semester.</p>
<p><br><br><br><br></p>
<p><strong>Bootstrapping FAQ</strong></p>
<ul>
<li>Isn’t it a problem that we could sample the same case multiple times?
<ul>
<li>e.g., Case 12 is sampled 3 times.</li>
<li>This just means that Case 12 is representative of 3 people in this sample.</li>
</ul></li>
<li>What’s the magic number of resamples?
<ul>
<li>1000 will be good enough for us.</li>
<li>Too little and we won’t get a good estimate of sampling variation.</li>
<li>Too large and the process will take too long.</li>
</ul></li>
<li>Why the middle 95% instead of 100% (the full range)?
<ul>
<li>Ideally, we want the histogram above to show <em>every possible sample</em> from the broader population – there are infinitely many of these!</li>
<li>The full distribution (which is only approximated by the histogram) goes from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>!</li>
<li>The 100% range would tell us: a plausible set of values for the true population value is <span class="math inline">\((-\infty, +\infty)\)</span>.</li>
<li>Not very useful!</li>
</ul></li>
</ul>
<p><br><br><br><br></p>
<p><strong>Assumptions of bootstrapping</strong> (<em>as described by the procedure above</em>)</p>
<ul>
<li>We assume that our sample is representative of the broader population.</li>
<li>We assume that our cases are <strong>independent</strong>.
<ul>
<li>More precisely, we assume that our <em>residuals</em> are independent.</li>
<li>Once we subtract off the “explainable part” of the response (leaving the residual), these errors (residuals) for different cases are not related to each other.</li>
</ul></li>
<li>Examples of violations of independence:
<ul>
<li>Cases are repeated measurements for an individual. (e.g., health measurements at multiple time points)</li>
<li>Cases share some spatial relatedness.</li>
<li>Cases share some temporal relatedness.</li>
</ul></li>
<li>Want to know more? Take Correlated Data at Mac!</li>
</ul>
<p><br><br><br><br></p>
</div>
<div id="exercises-5" class="section level2 unnumbered">
<h2>Exercises</h2>
<p>A template RMarkdown document that you can start from is available <a href="template_rmds/12-bootstrapping.Rmd">here</a>.</p>
<div id="data-setup" class="section level3 unnumbered">
<h3>Data setup</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)

experiment &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://www.dropbox.com/s/cwhhr0vjibw64tx/experiment_spring_2020.csv?dl=1&quot;</span>)

<span class="co"># Rename the variables</span>
<span class="kw">colnames</span>(experiment) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;timestamp&quot;</span>, <span class="st">&quot;arm&quot;</span>, <span class="st">&quot;rtime&quot;</span>, <span class="st">&quot;vid_games&quot;</span>, <span class="st">&quot;sports&quot;</span>, <span class="st">&quot;drive&quot;</span>, <span class="st">&quot;hand&quot;</span>)

<span class="co"># Clean up the &quot;hand&quot; variable labels</span>
experiment &lt;-<span class="st"> </span>experiment <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(
        <span class="dt">hand =</span> <span class="kw">case_when</span>(
            hand<span class="op">==</span><span class="st">&quot;Right-handed&quot;</span> <span class="op">~</span><span class="st"> &quot;Right&quot;</span>,
            hand<span class="op">==</span><span class="st">&quot;Left-handed&quot;</span> <span class="op">~</span><span class="st"> &quot;Left&quot;</span>
        )
    )</code></pre></div>
</div>
<div id="exercise-1-5" class="section level3 unnumbered">
<h3>Exercise 1</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Could being a video gamer, athlete, or regular driver confound the relationship between treatment and reaction time? Make plots to justify.</p></li>
<li><p>If we had performed this experiment in a much larger sample, would you expect these variables to be confounders? Explain. (Note: we’ll revisit the study design aspect (randomized experiment) in more detail next class.)</p></li>
<li><p>Based on your investigations, fit a model that will allow you to estimate the isolated (causal) effect of loud distractions on reaction times.</p></li>
<li><p>Obtain a 95% bootstrap confidence interval for this isolated (causal) effect. In order to ensure that your bootstrapping results don’t keep changing each time you run the code, put <code>set.seed(155)</code> at the top of the code chunk where you perform bootstrapping. If you get an error about missing values, add <code>, na.rm = TRUE</code> to the <code>quantile()</code> function.</p></li>
<li><p>What is the magnitude of a real, meaningful difference to you? Does your confidence interval provide evidence for a real difference? Briefly explain.</p></li>
</ol>
<p><br><br></p>
</div>
<div id="exercise-2-5" class="section level3 unnumbered">
<h3>Exercise 2</h3>
<p><strong>Research question:</strong> Does the isolated (causal) effect of distractions differ among video gamers and non-gamers?</p>
<ol style="list-style-type: lower-alpha">
<li><p>Answering this question involves a more complex model than we have seen before. Fit the model below, and first make sure that you understand how the R syntax <code>rtime ~ arm*vid_games + sports</code> translates to the coefficients that result in the full model formula.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_interact &lt;-<span class="st"> </span><span class="kw">lm</span>(rtime <span class="op">~</span><span class="st"> </span>arm<span class="op">*</span>vid_games <span class="op">+</span><span class="st"> </span>sports, <span class="dt">data =</span> experiment)
<span class="kw">summary</span>(mod_interact)</code></pre></div></li>
<li><p>Write the simpler model formulas for (1) non-gamers and (2) video gamers. Verify that these model formulas are multiple linear regression models. (Before, when our interaction models only included the two variables that were interacting, this process would give us simple linear regression models.)</p></li>
<li><p>Interpret the <code>armTreatment</code> coefficient in the non-gamer and the gamer model formulas. Based on this, explain why the <code>armTreatment:vid_gamesYes</code> coefficient answers this research question.</p></li>
<li><p>Obtain a 95% bootstrap confidence interval for the <code>armTreatment:vid_gamesYes</code> coefficient. (Use <code>set.seed(155)</code> again in your code chunk. If you get an error about missing values, add <code>, na.rm = TRUE</code> to the <code>quantile()</code> function.)</p></li>
<li><p>What is the magnitude of a real, meaningful difference in the causal effect for you? Does your confidence interval provide evidence for a real difference? Briefly explain.</p></li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="experiment.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="causal-inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
