<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Topic 8 Interaction Models | STAT 155: Introduction to Statistical Modeling</title>
  <meta name="description" content="This is the class website for STAT 155 at Macalester College." />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Topic 8 Interaction Models | STAT 155: Introduction to Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the class website for STAT 155 at Macalester College." />
  <meta name="github-repo" content="lmyint/155_spring_2020" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Topic 8 Interaction Models | STAT 155: Introduction to Statistical Modeling" />
  
  <meta name="twitter:description" content="This is the class website for STAT 155 at Macalester College." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-linear-regression.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #2a211c; color: #bdae9d; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; background-color: #2a211c; color: #bdae9d; border-right: 1px solid #bdae9d; }
td.sourceCode { padding-left: 5px; }
pre, code { color: #bdae9d; background-color: #2a211c; }
code > span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
code > span.dt { text-decoration: underline; } /* DataType */
code > span.dv { color: #44aa43; } /* DecVal */
code > span.bn { color: #44aa43; } /* BaseN */
code > span.fl { color: #44aa43; } /* Float */
code > span.ch { color: #049b0a; } /* Char */
code > span.st { color: #049b0a; } /* String */
code > span.co { color: #0066ff; font-style: italic; } /* Comment */
code > span.al { color: #ffff00; } /* Alert */
code > span.fu { color: #ff9358; font-weight: bold; } /* Function */
code > span.er { color: #ffff00; font-weight: bold; } /* Error */
code > span.wa { color: #ffff00; font-weight: bold; } /* Warning */
code > span.cn { } /* Constant */
code > span.sc { color: #049b0a; } /* SpecialChar */
code > span.vs { color: #049b0a; } /* VerbatimString */
code > span.ss { color: #049b0a; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { font-weight: bold; } /* Preprocessor */
code > span.at { } /* Attribute */
code > span.do { color: #0066ff; font-style: italic; } /* Documentation */
code > span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
code > span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
code > span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">STAT 155: Intro to Stat Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a><ul>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-1-124"><i class="fa fa-check"></i>Week 1: 1/24</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-2-127---131"><i class="fa fa-check"></i>Week 2: 1/27 - 1/31</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-3-23---27"><i class="fa fa-check"></i>Week 3: 2/3 - 2/7</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-4-210---214"><i class="fa fa-check"></i>Week 4: 2/10 - 2/14</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html#week-5-217---221"><i class="fa fa-check"></i>Week 5: 2/17 - 2/21</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a><ul>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html#troubleshooting"><i class="fa fa-check"></i>Troubleshooting</a></li>
</ul></li>
<li class="part"><span><b>I Describing and Visualizing Data</b></span></li>
<li class="chapter" data-level="1" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html"><i class="fa fa-check"></i><b>1</b> Welcome and Motivation</a><ul>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#introductions"><i class="fa fa-check"></i>Introductions</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#a-taste-of-data-visualization-in-r"><i class="fa fa-check"></i>A taste of data visualization in R</a><ul>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#warm-up"><i class="fa fa-check"></i>Warm-up</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-1"><i class="fa fa-check"></i>Phase 1</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-2"><i class="fa fa-check"></i>Phase 2</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-3"><i class="fa fa-check"></i>Phase 3</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-4"><i class="fa fa-check"></i>Phase 4</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-5"><i class="fa fa-check"></i>Phase 5</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-6"><i class="fa fa-check"></i>Phase 6</a></li>
<li class="chapter" data-level="" data-path="welcome-and-motivation.html"><a href="welcome-and-motivation.html#phase-7"><i class="fa fa-check"></i>Phase 7</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html"><i class="fa fa-check"></i><b>2</b> Univariate Visualization and Data Summaries</a><ul>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#learning-goals"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#discussion"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#exercises"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#part-1"><i class="fa fa-check"></i>Part 1</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#part-2"><i class="fa fa-check"></i>Part 2</a></li>
<li class="chapter" data-level="" data-path="univariate-visualization-and-data-summaries.html"><a href="univariate-visualization-and-data-summaries.html#extra"><i class="fa fa-check"></i>Extra!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html"><i class="fa fa-check"></i><b>3</b> Bivariate Visualization - Part 1</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#learning-goals-1"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercises-1"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#context-and-setup"><i class="fa fa-check"></i>Context and Setup</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-1.html"><a href="bivariate-visualization-part-1.html#extra-1"><i class="fa fa-check"></i>Extra!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html"><i class="fa fa-check"></i><b>4</b> Bivariate Visualization - Part 2</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#learning-goals-2"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercises-2"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-1-2"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-2-2"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-4-2"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-5-1"><i class="fa fa-check"></i>Exercise 5</a></li>
<li class="chapter" data-level="" data-path="bivariate-visualization-part-2.html"><a href="bivariate-visualization-part-2.html#exercise-6"><i class="fa fa-check"></i>Exercise 6</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Linear Regression Modeling</b></span></li>
<li class="chapter" data-level="5" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html"><i class="fa fa-check"></i><b>5</b> Modeling Concepts (Part 1)</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#learning-goals-3"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#new-groups"><i class="fa fa-check"></i>New Groups!</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#discussion-1"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercises-3"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-1-3"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-2-3"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-3-3"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-4-3"><i class="fa fa-check"></i>Exercise 4</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-1.html"><a href="modeling-concepts-part-1.html#exercise-5-2"><i class="fa fa-check"></i>Exercise 5</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html"><i class="fa fa-check"></i><b>6</b> Modeling Concepts (Part 2)</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#learning-goals-4"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#warm-up-1"><i class="fa fa-check"></i>Warm-up</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#discussion-2"><i class="fa fa-check"></i>Discussion</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercises-4"><i class="fa fa-check"></i>Exercises</a><ul>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercise-1-4"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="modeling-concepts-part-2.html"><a href="modeling-concepts-part-2.html#exercise-2-4"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#learning-goals-5"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#discussion-and-exercises"><i class="fa fa-check"></i>Discussion and Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="interaction-models.html"><a href="interaction-models.html"><i class="fa fa-check"></i><b>8</b> Interaction Models</a><ul>
<li class="chapter" data-level="" data-path="interaction-models.html"><a href="interaction-models.html#learning-goals-6"><i class="fa fa-check"></i>Learning Goals</a></li>
<li class="chapter" data-level="" data-path="interaction-models.html"><a href="interaction-models.html#discussion-and-exercises-1"><i class="fa fa-check"></i>Discussion and Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 155: Introduction to Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="interaction-models" class="section level1">
<h1><span class="header-section-number">Topic 8</span> Interaction Models</h1>
<div id="learning-goals-6" class="section level2 unnumbered">
<h2>Learning Goals</h2>
<ul>
<li>Understand what research questions can be answered with interaction models</li>
<li>Interpret coefficients in interaction models</li>
<li>Connect visualizations to the coefficient estimates in interaction models</li>
<li>Graphically/geometrically describe the “pictures” implied by different types of interaction models</li>
</ul>
<p><br><br><br><br></p>
</div>
<div id="discussion-and-exercises-1" class="section level2 unnumbered">
<h2>Discussion and Exercises</h2>
<p>A template RMarkdown document that you can start from is available <a href="template_rmds/08-interaction-models.Rmd">here</a>.</p>
<p>We will continue looking at the <code>diamonds</code> dataset.</p>
<ul>
<li><code>carat</code>: the weight of the diamond in carats (1 carat = 200 milligrams)</li>
<li><code>price</code>: price in US dollars</li>
<li><code>cut</code>: quality of the cut of the diamond (Fair, Good, Very Good, Premium, Ideal)</li>
<li><code>color</code>: Level 1 (best) to Level 7 (worst)</li>
<li><code>clarity</code>: Level 1 (worst) to Level 8 (best)</li>
<li><code>x</code>, <code>y</code>, and <code>z</code>: length, width, and depth respectively (in mm)</li>
<li><code>depth</code>: total depth percentage = z / mean(x, y)</li>
<li><code>table</code>: width of top of diamond relative to widest point</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)

diamonds &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://www.dropbox.com/s/9c8jqda4pwaq8i1/diamonds.csv?dl=1&quot;</span>)</code></pre></div>
<p><br><br><br></p>
<p><strong>Warm-up:</strong> Consider the model of <code>price</code> as a function of <code>clarity</code> and <code>carat</code>.</p>
<p><span class="math display">\[ E[\hbox{price}] = \beta_0 + \beta_1\hbox{clarityLevel_2} + \beta_2\hbox{clarityLevel_3} + \cdots + \beta_7\hbox{clarityLevel_8} + \beta_8\hbox{carat} \]</span></p>
<ul>
<li>Why was this called a <strong>parallel lines model</strong>?</li>
<li>Draw a picture of the relationships that this model implies and label the picture with the coefficients of the model.</li>
</ul>
<p><br><br><br></p>
<p><strong>Exercise 1:</strong> We looked at a scatterplot of <code>price</code> versus <code>carat</code> and boxplots of <code>price</code> versus <code>clarity</code>, but we haven’t looked at all three variables simultaneously. Let’s enrich the scatterplot to additionally show <code>clarity</code>.</p>
<p>We’ve seen that we can have <code>x</code>, <code>y</code>, <code>color</code>, and <code>fill</code> aesthetics (inside the <code>aes()</code>). How might we adapt the code below to show different color trend lines corresponding to the 8 clarity levels?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(diamonds, <span class="kw">aes</span>(<span class="dt">x =</span> carat, <span class="dt">y =</span> price)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_smooth</span>()</code></pre></div>
<p><br><br><br></p>
<p>If the relationship between the response <span class="math inline">\(y\)</span> and predictor <span class="math inline">\(x_1\)</span> differs depending on the value / categories of another predictor <span class="math inline">\(x_2\)</span>, we say that <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> <strong>interact</strong>. We capture this in our models with an <strong>interaction term</strong>: <span class="math inline">\(x_1 \times x_2\)</span>.</p>
<p><span class="math display">\[ E[y] = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_1 \times x_2 \]</span></p>
<p>The coefficient <span class="math inline">\(\beta_3\)</span> in front of the interaction term is called the <strong>interaction coefficient</strong>.</p>
<p><br><br><br></p>
<p>For now, let’s work with a subset of the data that just has two clarity levels.</p>
<p><span class="math display">\[ E[\hbox{price}] = \beta_0 + \beta_1\hbox{clarity2} + \beta_2\hbox{carat} + \beta_3\hbox{clarity2}\times\hbox{carat} \]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">diamonds_sub &lt;-<span class="st"> </span>diamonds <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">filter</span>(clarity <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Level_1&quot;</span>, <span class="st">&quot;Level_2&quot;</span>))

mod1 &lt;-<span class="st"> </span><span class="kw">lm</span>(price <span class="op">~</span><span class="st"> </span>clarity<span class="op">*</span>carat, <span class="dt">data =</span> diamonds_sub)
<span class="kw">summary</span>(mod1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ clarity * carat, data = diamonds_sub)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6051.1  -645.7  -112.8   485.6  6304.1 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -1480.56     103.76  -14.27   &lt;2e-16 ***
## clarityLevel_2       -1937.78     108.04  -17.94   &lt;2e-16 ***
## carat                 4209.79      72.51   58.06   &lt;2e-16 ***
## clarityLevel_2:carat  3660.46      76.76   47.69   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1247 on 9931 degrees of freedom
## Multiple R-squared:  0.911,  Adjusted R-squared:  0.9109 
## F-statistic: 3.387e+04 on 3 and 9931 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li><strong>Note:</strong> When you see a colon between two variables, the colon means a multiplication sign. (<code>clarityLevel_2:carat</code> is the product of the <code>clarityLevel_2</code> indicator variable and the <code>carat</code> variable.)</li>
</ul>
<p><br></p>
<p><strong>Model formula</strong></p>
<p><span class="math display">\[
\begin{align*}
E[\hbox{price}] &amp;= \beta_0 + \beta_1\hbox{clarity2} + \beta_2\hbox{carat} + \beta_3\hbox{clarity2}\times\hbox{carat} \\
&amp;= -1480.56 - 1937.78\,\hbox{clarity2} + 4209.79\,\hbox{carat} + 3660.46\,\hbox{clarity2}\times\hbox{carat}
\end{align*}
\]</span></p>
<p><br></p>
<p><strong>Model formula for clarity level 1</strong></p>
<p><span class="math display">\[
\begin{align*}
E[\hbox{price}] &amp;= -1480.56 - 1937.78\times 0 + 4209.79\,\hbox{carat} + 3660.46\times 0 \times\hbox{carat} \\
&amp;= -1480.56 + 4209.79\,\hbox{carat}
\end{align*}
\]</span></p>
<p><br></p>
<p><strong>Model formula for clarity level 2</strong></p>
<p><span class="math display">\[
\begin{align*}
E[\hbox{price}] &amp;= -1480.56 - 1937.78\times 1 + 4209.79\,\hbox{carat} + 3660.46\times 1 \times\hbox{carat} \\
&amp;= (-1480.56 - 1937.78) + (4209.79 + 3660.46)\,\hbox{carat} \\
&amp;= -3418.34 + 7870.25\,\hbox{carat}
\end{align*}
\]</span></p>
<p><br></p>
<p><strong>It is very helpful to draw a picture labeled with the coefficients.</strong></p>
<p><br></p>
<p>Coefficient interpretations:</p>
<ul>
<li><p>Intercept <span class="math inline">\(\beta_0\)</span>: -1480.56<br />
The average price for a zero carat, level 1 clarity diamond. (Could have made more meaningful by centering <code>carat</code>, but generally not interested in the intercept.)</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> for <code>carat</code>: 4209.79<br />
The slope for the clarity level 1 model. On average, diamond price increases by $4209.79 per carat increase <strong>in level 1 clarity diamonds</strong>. (This rate of change is different for clarity level 2 diamonds.)</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> for <code>clarityLevel_2</code>: -1937.78<br />
The change in y-intercept going from clarity level 1 to 2.<br />
On average, zero carat diamonds that are clarity level 2 are worth $1937.78 less than zero carat, clarity level 1 diamonds.</p></li>
<li><p><span class="math inline">\(\beta_3\)</span> for the interaction term (<code>clarityLevel_2:carat</code>): 3660.46<br />
The change in slope for the clarity level 2 vs. the clarity level 1 model. The average change in price per carat increase is 3660.46 ($/carat) higher for clarity level 2 vs. clarity level 1 diamonds.<br />
The slope is steeper for level 2. A carat is worth more for a level 2 clarity diamond.</p></li>
</ul>
<p><br><br><br></p>
<p><strong>Exercise 2:</strong> Fit a model with interaction between <code>clarity</code> and <code>carat</code> for the full diamonds dataset.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Write out the model formulas for clarity level 1, 2, … diamonds until you get the hang of it.</p></li>
<li><p>Draw a picture with the model lines for clarity level 1, 2, … 8 diamonds. Annotate this picture with the model coefficients.</p></li>
<li><p>Interpret the <code>clarityLevel_3</code> and <code>clarityLevel_3:carat</code> coefficients. Repeat for level 4 and onwards until you get the hang of it.</p></li>
<li><p>For which clarity level is a carat worth the most? How much is a carat worth on average?</p></li>
</ol>
<p><br><br><br></p>
<p><strong>Exercise 3:</strong> Now let’s consider diamond color (Level 1 is best and Level 7 is worst).</p>
<ol style="list-style-type: lower-alpha">
<li><p>What research question are you exploring when you fit a model with interaction between <code>color</code> and <code>carat</code>? Generalize this to a broader context.</p></li>
<li><p>Make a plot that allows you to explore potential interaction between <code>color</code> and <code>carat</code>. What are you looking to see in the plot? Do you think an interaction model is appropriate?</p></li>
<li><p>Fit the interaction model, and focus on the coefficients of substantive interest. Summarize your overall conclusions.</p></li>
</ol>
<p><br><br><br></p>
<p>The remainder of these exercises don’t require R.</p>
<p><br></p>
<p><strong>Exercise 4:</strong> We’ve seen interaction between a categorical and a quantitative variable. Two categorical variables can interact as well. Consider the model</p>
<p><span class="math display">\[
\begin{align*}
E[\hbox{winpercent}] = \beta_0 &amp;+ \beta_1\hbox{chocolateTRUE} \\
&amp;+ \beta_2\hbox{peanutyalmondyTRUE} + \beta_3\hbox{chocolateTRUE}\times\hbox{peanutyalmondyTRUE}
\end{align*}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li><p>Write out the model formulas for the non-chocolate candies and for the chocolate candies. Leave <code>peanutyalmondyTRUE</code> as-is without plugging in anything for it. (Similar to leaving <code>carat</code> as-is in the diamonds context.)</p></li>
<li><p>From part (a), interpret <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_2\)</span>. Then interpret <span class="math inline">\(\beta_0+\beta_1\)</span> and <span class="math inline">\(\beta_2+\beta_3\)</span>.</p></li>
<li><p>The mean <code>winpercent</code>s in all four combinations of <code>chocolate</code> and <code>peanutyalmondy</code> are shown below. From this information, determine the values of the model coefficients.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">candy <span class="op">%&gt;%</span>
<span class="st">    </span>dplyr<span class="op">::</span><span class="kw">group_by</span>(chocolate, peanutyalmondy) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">summarize</span>(<span class="dt">mean_winpercent =</span> <span class="kw">mean</span>(winpercent))</code></pre></div>
<pre><code>## # A tibble: 4 x 3
## # Groups:   chocolate [2]
##   chocolate peanutyalmondy mean_winpercent
##   &lt;lgl&gt;     &lt;lgl&gt;                    &lt;dbl&gt;
## 1 FALSE     FALSE                     42.5
## 2 FALSE     TRUE                      34.9
## 3 TRUE      FALSE                     57.3
## 4 TRUE      TRUE                      68.5</code></pre></li>
<li><p>Now interpret <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_2\)</span>, <span class="math inline">\(\beta_0+\beta_1\)</span>, and <span class="math inline">\(\beta_2+\beta_3\)</span> in a contextually meaningful way. Is nuttiness (<code>peanutyalmondy</code>) “better” in chocolate candies or in non-chocolate candies?</p></li>
</ol>
<p><br><br><br></p>
<p><strong>Exercise 5:</strong> Two quantitative variables can interact as well. In a model of <code>Price</code>, the <code>Mileage</code> and <code>Age</code> of a used car interact: the relationship between mileage and price differs depending upon the age of the car. Below, the yellow lines represent the relationship between price and mileage for 1 year old, 5 year old, and 10 year old used cars.</p>
<div class="figure">
<img src="images/fords.png" />

</div>
<ol style="list-style-type: lower-alpha">
<li>Based on this plot, what do you anticipate about the signs of the coefficients in the interaction model? (Don’t look ahead to the output below yet.)</li>
</ol>
<p><span class="math display">\[ E[\hbox{Price}] = \beta_0 + \beta_1 \hbox{Age} + \beta_2 \hbox{Mileage} + \beta_3 \hbox{Age}\times\hbox{Mileage} \]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Based on the model output below, write the model formulas relating <code>Price</code> to <code>Mileage</code> for cars that are 0 years (new), 5 years, and 12 years old.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fords &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://www.dropbox.com/s/wmb6ktyaw5c5jwf/Fords.csv?dl=1&quot;</span>)
fords_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Age<span class="op">*</span>Mileage, <span class="dt">data =</span> fords)
<span class="kw">summary</span>(fords_mod)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Age * Mileage, data = fords)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6950.1 -1254.4   -35.5  1124.6  7355.2 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.932e+04  2.256e+02   85.65   &lt;2e-16 ***
## Age         -1.523e+03  6.042e+01  -25.21   &lt;2e-16 ***
## Mileage     -1.349e-01  4.835e-03  -27.91   &lt;2e-16 ***
## Age:Mileage  1.320e-02  6.488e-04   20.34   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1899 on 606 degrees of freedom
##   (25 observations deleted due to missingness)
## Multiple R-squared:  0.8342, Adjusted R-squared:  0.8334 
## F-statistic:  1016 on 3 and 606 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Given (b), what does the interaction coefficient help us learn about the relationship between <code>Price</code> and <code>Mileage</code>?</p></li>
<li><p><em>Extra (not required but good practice):</em> Interpret each of the coefficients in the above model.</p></li>
</ol>
<p><br><br><br></p>
<p><strong>Interlude:</strong> Take a moment to think about the theme of these interaction exercises. In all of them, we have used interaction terms to describe how the relationship between a variable and the response is <strong>modified</strong> by the value of another variable. For this reason, interaction is also called <strong>effect modification</strong>.</p>
<ul>
<li>Diamond clarity and color modify the effect of size on price. Note that effect modification/interaction is symmetric, so we can also say that diamond size modifies the effect of clarity and color on price. However, usually with interaction between a quantitative and a categorical variable, we describe it in the first way.</li>
<li>Chocolatiness modifies the effect of nuttiness on candy popularity. Symmetrically, nuttiness modifies the effect of chocolatiness on candy popularity.</li>
</ul>
<p><br><br><br></p>
<p><strong>Exercise 6:</strong> Confounding and interaction are not the same idea.</p>
<ol style="list-style-type: lower-alpha">
<li>Draw or describe how the situation below could arise:
<ul>
<li><code>carat</code> does confound the relationship between <code>clarity</code> and <code>price</code>.</li>
<li>There is no interaction between <code>carat</code> and <code>clarity</code>.</li>
</ul></li>
<li>Draw or describe how the situation below could arise:
<ul>
<li><code>carat</code> does not confound the relationship between <code>clarity</code> and <code>price</code>.</li>
<li>There is interaction between <code>carat</code> and <code>clarity</code>.</li>
</ul></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-linear-regression.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
